module.exports = {
  events: {
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    TYPING: "TYPING",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VERIFY_USER: "VERIFY_USER",
    LOGOUT: "LOGOUT",
  },
};
